defaults:
  - _self_
  - env: pendulum
  - alg: PPO
name: "default"
num_eval_trials: 10
eval_frequency: 50

hydra:
  job:
    name: ${name}
  run:
      dir: experiments/${name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
